### PR TITLE
feat: added copilot.lua and documented Git tools

### PR DESCRIPTION
**Pull request by soulfresh**
### What does this PR do?

Integrates Copilot with `nvim-cmp`. Copilot previews are shown in ghost text while autocomplete suggestions appear in the normal dropdown. To get these two plugins playing nicely together I had to prevent the Tab key from cycling through autocomplete menu items. Instead, you'll need to use `<C-n>` and `<C-p>` (next/previous). I've also written a bunch of documentation around the interactions.

Long term, I think it might be better to move the copilot suggestions into the autocomplete dialog using `copilot-cmp` but I couldn't get it working.

### CODE REVIEW

**Review by tommymetz — APPROVED** [review]
@soulfresh works good. Gotta get used to the <C-n> and <C-p> tho which is odd. Could we do <C-n> and <C-p> instead? I know you mentioned its from emacs or something but curious if we could override that.

**Comment by soulfresh** [comment]
Sorry...your message got garbled somehow. I'm not sure what you want the new mapping to be. `Ctrl n/p` is a default mapping that can be used to navigate most Vim lists so it's worth getting used to. However, I'm open to adding another option for moving through the autocomplete list.

**Comment by tommymetz** [comment]
@soulfresh ok all good. Just seems odd to me that it's not `j` and `k`. But I'll start trying to get used to it.

**Comment by tommymetz** [comment]
I mean I get it not. being `j` and `k`. But why not `<C-j>` and `<C-k>`. All good tho.

**Comment by soulfresh** [comment]
`<C-j/k>` can be used for navigating up/down a line when in insert mode. We could try a couple things though:

- Remap `<C-j/k>` to a function that detects if the autocomplete is open and then chooses the appropriate call to make
- Try Alt or Command j/k. Alt might work best between iTerm and Neovide

**Pull request merged**
